language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages: 
      - ffmpeg
install: 
  - "pip install -r requirements_test.txt"
  - "python setup.py install"
before_script:
  - psql -c 'create database zoudb;' -U postgres
script: py.test
